# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_auto_20170524_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=50)),
                ('offer_description', models.TextField(max_length=200)),
                ('discount', models.PositiveIntegerField(blank=True, max_length=2, null=True)),
                ('expires', models.DateField()),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product')),
            ],
        ),
    ]
