# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20170524_1400'),
        ('offers', '0002_auto_20170529_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='products',
        ),
        migrations.AddField(
            model_name='offer',
            name='products',
            field=models.ManyToManyField(to='catalog.Product'),
        ),
    ]
